#dist: trusty
#sudo: required

language: python
python:
  - "2.7"

install:
  - pip install .
  - pip install 'pytest>=2.9' pytest-cov pytest-timeout coveralls
script:
#  - py.test --cov=workflows
  - py.test
#after_success:
#  - coveralls
