#dist: trusty
#sudo: required

language: python
python:
  - "2.7"

before_install:
  - sudo apt-get install libboost-dev

install:
  - pip install .
  - pip install 'pytest>=3'
# pytest-cov pytest-timeout coveralls
script:
#  - py.test --cov=workflows
  - py.test
#after_success:
#  - coveralls
